# == Opciones Base ==
# Soporte para scroll con el mouse y hacer click en paneles
set -g mouse on

# Renumerar ventanas automáticamente cuando una se cierra
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# Passthrough de eventos de foco (importante para Neovim)
set-option -g focus-events on

# Reducir el lag del escape (vital en Neovim)
set-option -sg escape-time 10

# == Colores y Terminfo (Evitar que se rompa Zsh/Nvim) ==
# Hacer creer a Tmux que soporta 256 colores nativamente
set-option -g default-terminal "tmux-256color"
# Sobrescribir el terminal para forzar TrueColor (RGB) específicamente al usar Ghostty o cualquier otra moderna
set-option -sa terminal-features ',xterm-ghostty:RGB'
set-option -ga terminal-overrides ',xterm-ghostty:Tc'

# == Diseño de la Barra de Estado (Catppuccin) ==
set-option -g status-position top

# Plugins de Tmux (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Configuración del tema Catppuccin (flavor: mocha)
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_status_background 'default'

# Módulos de la barra de estado
set -g @catppuccin_status_modules_right 'directory session date_time'
set -g @catppuccin_date_time_text '%H:%M  %d %b'

# Inicializar TPM (debe ser la última línea)
run '~/.tmux/plugins/tpm/tpm'


